# yamllint disable rule:line-length
---
stages:
  - lint
  - image
  - test
  - deploy

variables:
  _BUILDAH_STARTED_IN_USERNS: ''
  BUILDAH_ISOLATION: chroot
  STORAGE_DRIVER: vfs
  BUILDAH_FORMAT: docker

yamllint:
  stage: lint
  needs: []
  image: pipelinecomponents/yamllint
  only:
    - main
  allow_failure: false
  script:
    - yamllint .

test-create-image:
  stage: image
  needs:
    - yamllint
  image: docker.io/buildah/buildah
  only:
    - merge_request
  script:
    - export DIR="."
    - export NAME="kube-c1-dev"
    - buildah build-using-dockerfile --tag "${NAME}" "${DIR}"

create-image:
  stage: image
  needs:
    - yamllint
  image: docker.io/buildah/buildah
  only:
    - main
  script:
    - export DIR="."
    - export NAME="kube-c1"
    - buildah build-using-dockerfile --tag "${NAME}" "${DIR}"
    - buildah push --creds "${CI_REGISTRY_USER}:${CI_JOB_TOKEN}" "${NAME}" "docker://${CI_REGISTRY_IMAGE}/${NAME}:latest" && exit 0 || true
    - buildah push --creds "${CI_REGISTRY_USER}:${CI_JOB_TOKEN}" "${NAME}" "docker://${CI_REGISTRY_IMAGE}/${NAME}:latest"

test-full:
  stage: test
  image: node:latest
  before_script:
    - npm install --force
  script:
    - npm run test

test-merge:
  stage: test
  image: node:latest
  only:
    - merge_request
  before_script:
    - npm install --force
  script:
    - npm run test


deploy-regcred:
  stage: deploy
  image: bitnami/kubectl
  needs:
    - yamllint
  only:
    - main
  script:
    - kubectl get secrets | grep liu-gitlab-regcred && exit 0
    - kubectl create secret docker-registry liu-gitlab-regcred --docker-server=https://gitlab.liu.se:5000 --docker-username=k8s --docker-password=${REGISTRY_PASSWORD}
    - kubectl get secret liu-gitlab-regcred

deploy:
  stage: deploy
  image: bitnami/kubectl
  only:
    - main
  needs:
    - deploy-regcred
    - create-image
    - yamllint
  script:
    - kubectl apply -f c1-deploy.yaml
    - kubectl rollout restart deployment c1-deployment
